name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Firebase Hosting
        run: |  
          npm install -g firebase-tools
          firebase login
          firebase use --add teishoku-17e3d
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
